safe: true
#source: https://github.com/adicu/adicu.github.com
#destination: ~/working/adicu.github.com/
lsi: false
permalink: /:month-:day-:year/:title.html
exclude: [newpost.sh, .gitignore, gcal_template.md, Gemfile, Gemfile.lock, Gruntfile.coffee, package.json, README.md, less, node_modules, develop]
paginate: 10
base: "http://adicu.com"
paginate_path: "blog/page:num"
markdown: redcarpet
pygments: true

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]
